### ISSUE TITLE
TIBCO EMS stack not getting created with the AWS quick start templates

### ISSUE THREAD

**Issue by sumanchatterjee3** [aws-quickstart/quickstart-tibco-ems#9]
Hi,
I am trying to run the EMS quick start templates for aws. While running them I see that the VPC stack is getting created successfully, the Bastion stack has been created successfully. While creating the EMS stack it is failing while creating the EMS Server instance.
I have tried both the options (ie: New VPC as well as Existing VPC approaches). The error is still at the same place. I have Administrator access on the account so I am sure it not a permission issue. 
I am attaching the Error Log for the EMS Stack only.
Can you please help?

[TIBCOEMSQuickStart-EMSStack-Error.log](https://github.com/aws-quickstart/quickstart-tibco-ems/files/2509668/TIBCOEMSQuickStart-EMSStack-Error.log)

Thanks,
Suman

**Comment by rflather-tibco** [comment]
Suman,

I took a look at this today, and could not duplicate your error. I was able to successfully complete the TIBCO-EMS QuickStart without any errors.
When you ran the TIBCO-EMS QuickStart, did you provide a valid S3 bucket with the TIBCO EMS 8.4 installer (TIB_ems_8.4.0_linux_x86_64.zip) in it? This is required.

**Comment by sumanchatterjee3** [comment]
Hi,

Yes I did provide a valid S3 bucket name that contains the installer.zip file. And I have made sure that it has proper permissions.

Thanks,
Suman

**Comment by rflather-tibco** [comment]
All I can tell you is to try it again, and ensure all of your inputs are correct. If it should continue to fail, please let me know all of you inputs to the template, and any other errors produced.

**Comment by sumanchatterjee3** [comment]
Hi,

After numerous failed efforts I have been finally able to find the exact error. This error was in the cfn.-init.log file of the EMS Server instance. 

Below is the error snippet. I am attaching the entire log file as well

ToolError: Failed to retrieve https://tibcoems.s3.amazonaws.com/TIB_ems_8.4.0_linux_x86_64.zip: HTTP Error 400 : <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidRequest</Code><Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message><RequestId>296243FD0B998215</RequestId><HostId>bBTj9c3E4eYigJDJ9Xp0or8KbYsumkLyJc8Nva8KMkWjmoKdprEmQtf5z5roS/gFeAy17vrw/58=</HostId></Error>
2018-11-15 17:41:12,893 [DEBUG] CloudFormation client initialized with endpoint https://cloudformation.us-east-2.amazonaws.com
2018-11-15 17:41:12,893 [DEBUG] Signaling resource EMSServerInstance1 in stack TIBCO-EMS-EMSStack-196UBG0DMRTUN-EMSServerStack-11CLAFIJSQNQ8 with unique ID i-0a4746c6c511be1ae and status FAILURE

I am not sure as to why we are getting this errors? I have verified that the files have public read access.

Thanks,
Suman
[Error.log](https://github.com/aws-quickstart/quickstart-tibco-ems/files/2586600/Error.log)

**Comment by rflather-tibco** [comment]
First I would verify that the S3 bucket does exist, has the proper
permissions, and that the EMS zip file is there and has the appropriate
permissions.
If the problem still exists, I suggest you reach out to AWS support.

**Comment by sumanchatterjee3** [comment]
Hi,

I was finally able to resolve the issue. The issue was, I had kept the installables in an S3 bucket which had HMAC-SHA256 signature authentication.
Due to this the rest call for pulling the installable was failing and hence the entire process was failing.

I changed the region to a different region with a new bucket and then tried again and this resolved the issue.

Thanks.
